### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by YoelMonsalve** [kurokuro15/api-dolar-bcv#1]
Hola, también soy desarrollador y luce interesante. Sería bueno acompañar con códigos de ejemplos de uso, de otro modo es un poco difícil deducir cómo se puede utilizar o incorporar a un proyecto. 

Noto que la conexión a `DB` se realiza a nivel de `Javascript` (_frontend_), así que asumo la idea es funcionar como una App cliente que corra embebida en la ventana del navegador.

**Comment by kurokuro15** [comment]
Hola @YoelMonsalve, gracias por tomarte el tiempo de abrir una issue en este repo. 

Primero, en pro de aclaraciones, este repo fue principalmente realizado como prueba, de hecho no sé por qué lo tengo público jeje, el repositorio que está con mejor acabado son los siguientes: [bcv-api](https://github.com/kurokuro15/bcv-api) que está escrito en javascript usando DenoJS como runtime, está pensado para levantarse como un servicio/servidor que escucha y devuelve una respuesta GET, básicamente una API sin autenticación ni manejo de casi nada, puesto que fue principalmente para darle uso a este otro repo [bcv-scrapper-aws](https://github.com/kurokuro15/bcv-scrapper-aws) cuyo objetivo era realizar la extracción de la relación bolivar-dolar & otras monedas a través de una función 'serverless' o lambda function desplegada en el servicio del mismo nombre de AWS. 

Por otro lado, los códigos de ejemplo y usabilidad deberías poder encontrarlos en el readme.md  de los repositorios que te indique, dado que como dije, este no es más que un predecesor de dichos códigos que si están o estuvieron en producción.

Aún así, agradezco mucho tú feedback y espero disponer de tiempo para iterar los repositorios que he creado y mejorarlos en el tiempo 😄
